---
name: Linting
on:
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    name: YAML Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: YAML Lint
        uses: karancode/yamllint-github-action@v2.1.0
        with:
          yamllint_comment: true
          yamllint_config_filepath: .github/config/yaml-linter.yaml
          yamllint_format: parsable
