---
name: Linting
on:
  pull_request:
    branches:
      - main

jobs:
  shell-lint:
    name: Shell Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
