---
name: Linting
on:
  pull_request:
    branches:
      - main

jobs:
  shell-lint:
    name: Shell Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'
